<a href="https://colab.research.google.com/github/gagan-iitb/DS-503/blob/main/Assignments/Assignment2_Starter_Code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Question 1: Collaborative Filtering

Load Dataset from Github

Prepare the set Y (of users who have rated all 100 items from the training set)

1. Write a function that implements the Pseudo Inverse Approach using the known ratings of the user X and returns the weights for each user in set Y that yield a closest least square approximation. (You are solving: R_y * W_y = R_x).
2. Using these weights estimate the unknown ratings for x
3. Write a function to calculate the RMSE (root mean square error) for the ratings in the validation set for all users in the validation set

Implement Nearest Neighbor Collaborative Filtering
a. Find K most similar items to each item in the training dataset (Note. this set is the same for all users) using their Pearson Correlation Coefficient. Store these weights.
b. Estimate the unknown ratings for a user X using the weighted combinations of the average known ratings of the K most similar items in the training set.
c. Adjust for the deviations of user X and the items from the mean ratings of the items in the dataset.
Note: You can use the validation set to tune the correction factors and test the expected accuracy of your method.

Factorize the Rating matrix of the training set into a product of 2 matrices P and Q such that the number of columns in P = number of rows in Q = a small number, r (<100). Compute the RMSE for different values of r using the known entries in the training set and plot RMSE vs. r. Pick a value of "r" that is at the elbow of the curve (or any other reasonable choice). 

P martix contains the latent features for each user.
Q matrix contains the latent features for each item.

For estimating unknown ratings of a user X, we need to estimate his/her latent features using their known ratings and use them to predict the unknown ratings. You can use the validation set to tune these parameters.

# Problem 02: Network Flow Summaries

In [ ]:

from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt 
import numpy as np 
import os
import pandas as pd

In [ ]:
nRowsRead = None
df1 = pd.read_csv('/content/Unicauca-dataset-April-June-2019-Network-flows11.csv', delimiter=',', nrows = nRowsRead)
df1.dataframeName = 'Unicauca-dataset-April-June-2019-Network-flows.csv'
nRow, nCol = df1.shape
print(f'There are {nRow} rows and {nCol} columns')

There are 4999 rows and 50 columns

In [ ]:
df1.head(10)

                           flow_key  ...  web_service
0  3acee4f4ea001cd5e6d9584d4036b53d  ...         DHCP
1  974ec5991b439c9a7176b88be0c90df0  ...         DHCP
2  3acee4f4ea001cd5e6d9584d4036b53d  ...         DHCP
3  974ec5991b439c9a7176b88be0c90df0  ...         DHCP
4  cfa7c2740072befaa89c202499729e08  ...         ICMP
5  974ec5991b439c9a7176b88be0c90df0  ...         DHCP
6  3acee4f4ea001cd5e6d9584d4036b53d  ...         DHCP
7  3acee4f4ea001cd5e6d9584d4036b53d  ...         DHCP
8  974ec5991b439c9a7176b88be0c90df0  ...         DHCP
9  3acee4f4ea001cd5e6d9584d4036b53d  ...         DHCP

[10 rows x 50 columns]

# *Problem* 03 Spell Check for Hotel Reviews

In [ ]:
nRowsRead = None
df1 = pd.read_csv('/content/chennai_reviews.csv', delimiter=',', nrows = nRowsRead)
df1.dataframeName = 'Unicauca-dataset-April-June-2019-Network-flows.csv'
nRow, nCol = df1.shape
print(f'There are {nRow} rows and {nCol} columns')

There are 4768 rows and 9 columns

In [ ]:
df1

                 Hotel_name  ... Unnamed: 8
0       Accord Metropolitan  ...        NaN
1       Accord Metropolitan  ...        NaN
2       Accord Metropolitan  ...        NaN
3       Accord Metropolitan  ...        NaN
4       Accord Metropolitan  ...        NaN
...                     ...  ...        ...
4763  Hyatt Regency Chennai  ...        NaN
4764  Hyatt Regency Chennai  ...        NaN
4765  Hyatt Regency Chennai  ...        NaN
4766  Hyatt Regency Chennai  ...        NaN
4767  Hyatt Regency Chennai  ...        NaN

[4768 rows x 9 columns]